repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: check-added-large-files

- repo: https://github.com/anthonyharrison/secret_scanner
  rev: 1.4.0
  hooks:
    - id: secrets-scanner
